### ISSUE TITLE
Bower is not installing

### ISSUE THREAD

**Issue by warlock-jay** [actions-on-google/smart-home-nodejs#109]
In step 9 bower is not installing,it's giving error like this.
**** npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/  ***
So i tried yarn then it gave 
**** npm WARN deprecated yarn@1.3.2: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install  *****
10 days back bower is working ,now it's not working.
what's the solution?

**Comment by Fleker** [comment]
It looks like bower may be deprecated. I'll look into it.

**Comment by ash-lat** [comment]
same issue
Any update?

**Comment by Fleker** [comment]
It's on my to-do list tomorrow.

**Comment by ash-lat** [comment]
@Fleker 
Were you able to find a workaround for the issue?

**Comment by Fleker** [comment]
Bower is being deprecated. It doesn't seem like I'm having issues installing from bower at the moment. At some point everything will have to move to npm/yarn. The Polymer team is aware of this for v3, although a migration will take some time.

I began to follow Bower's migration guide. However, a handful of dependencies are not installing, like [iron-icons](https://github.com/PolymerElements/iron-icons) because it has a `package.json` file without a package version, causing yarn's installation process to fail:

`error An unexpected error occurred: "Can't add \"@bower_components/iron-icon\": invalid package version undefined.".`

I think you should still be able to use bower, as the installation seems to work. I will continue looking into a more long-term solution.

**Comment by yoicks** [comment]
Hello, I encountered the same problem.
It's giving error like this:
`npm install -g bower`
npm WARN deprecated bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
C:\Users\user\AppData\Roaming\npm\bower -> C:\Users\user\AppData\Roaming\npm\node_modules\bower\bin\bower
'+ bower@1.8.4
updated 1 package in 7.712s

`bower install`
bower app-layout#^2.0.4         ENOGIT git is not installed or not in the PATH

@Fleker mentioned that we should still be able to use bower, but it seems not working now. Any updated solutions? Thanks.

**Comment by Fleker** [comment]
@yoicks it looks like your issue is related to not having [git in your PATH](https://stackoverflow.com/questions/20666989/bower-enogit-git-is-not-installed-or-not-in-the-path).

Bower has been working for me, albeit with the warning.

**Comment by sam0910** [comment]
Find ‘bower-away’ on gibhub,
and install it, then install bower again, 
This will install all defendencies and working just fine to me.

**Comment by Fleker** [comment]
The sample has now been significantly updated. It has moved away from Bower and now uses Polymer 3 and npm.
