### ISSUE TITLE
Clarification needed on the login page for smart light example.

### ISSUE THREAD

**Issue by sakthisg** [actions-on-google/smart-home-nodejs#157]
Hi
1. Is there any specific reason for having login in the frontend(username :rick and password:oldman? 
2. After npm start is there any time limit for connecting from google assistant (mobile device) for this example? After  a day if i tell google assistant (mobile) to change lamp color..it says the invocation is not available at this moment eventhough the server is running. Only method is i have to redo all the steps from Readme.md

**Comment by sakthisg** [comment]
1. From google assistant i am logging with my login, still unclear for me why do we need this login in the front end. Could you please clarify?

**Comment by Fleker** [comment]
You need to associate your Google account with the account that you have with the smart home service. Behind the scenes the Google Assistant uses OAuth to pass tokens around so that the two can communicate without directly sending private information.

**Comment by sakthisg** [comment]
Thanks nick..for clarifications.
https://youtu.be/996OiexHze0 this was helpful for oath2 understandings..is
there any video lessons for beginners for specific to oath2 Google
assistant topic?

**Comment by Fleker** [comment]
This platform uses standard OAuth flows, so there's nothing particularly specific you need to learn. But one good place to start [is this Medium post](https://medium.com/google-developer-experts/setup-an-authorization-server-less-for-your-actions-on-google-application-ff56f0328cf8) which walks through a lot of the setup using a 3rd party OAuth service. There's a few steps at the end which you need to do separately in order to get the access token, but it should be pretty handy.
