### ISSUE TITLE
Smart Home display - thermostat issues

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#200]
One of my users has the Lenovo display, but when he queries or sets the temperature, it reboots..!

On the Home Hub, i notice that when I change the temp on a thermostat, it first issues a query, then the execute request, but the Home Hub returns an error "that device doesn't seem to be connected to WiFi" - or something similar.
It looks like there' s a timing issue here where it's reporting before the execute happens.

**Comment by Fleker** [comment]
The Lenovo display reboots on a query?

When you return a query or execute, what states are you passing? Are you including the `online` state? If that is not included or set to false, it may be interpreted as not being available due to being considered offline.

In your cases, are these a specific commercial brand, or your own project?

**Comment by madgeni** [comment]
I don't return one for execute - it's not documented as a pre-req? 
I do for queries

**Comment by madgeni** [comment]
the addition of online: true doesn't resolve this. definitely feels like some timing issue.

**Comment by Fleker** [comment]
How long is it taking to return a response?

**Comment by madgeni** [comment]
Yep - it's a timing issue with the hardware. executing, but taking too long to come back - it's not a Google issue (imo)
