### ISSUE TITLE
How to call Report state after SYNC

### ISSUE THREAD

**Issue by abhitheawesomecoder** [actions-on-google/smart-home-nodejs#224]
"The ReportState API should also be called right after a SYNC intent. After a SYNC intent, new devices might have been added, and in order to set their initial states, a Report State call should follow."

How can I run code for report state when Query has already return. 
After return statement its not possible to call a code

**Comment by abhitheawesomecoder** [comment]
I am using node js

**Comment by abhitheawesomecoder** [comment]
how can i get the notification at my endpoint after sync process is successful, because before that if I run report state then i get 404  error ,requested resource could not be found .

**Comment by Fleker** [comment]
It depends on your server configuration. You could start a cloud function before responding, with this second function adding a notable delay before responding, or your server may be able to kick off another task after responding, or if you use gRPC it should be a bit easier.

**Comment by i8beef** [comment]
Also having trouble with this. Requiring clients to implement an asynchronous work flow based on a request you initialize from your side, and requiring an artificial delay and specific order to the response pipeline, presupposes a lot more infrastructure on the client than should be necessary. This makes a lot more sense if you simply make a second request after SYNC is successful to get current complete state. 

Which I believe you already do with a post-SYNC QUERY, or at least I think you used to... Pushing the burden onto your clients to _guess_ when a SYNC completed, and then do something like queuing a post response extra request at an arbitrary delay, isn't really even a _short_ term solution here.

Could we maybe tie this off a QUERY intent instead? I.e., whenever we receive a query intent we reportState for the requested devices on that as well? If we get a _full_ QUERY request (all devices) immediately following a successful SYNC intent, then we eliminate all the uncertainty, as it would be a Google initiated instruction rather than a random guess of "maybe my SYNC succeeded and HomeGraph has synced?".

**Comment by jcyh0120** [comment]
I want to review the google smart home document and didn't find the description
"The ReportState API should also be called right after a SYNC intent. After a SYNC intent, new devices might have been added, and in order to set their initial states, a Report State call should follow."

What is the preferred flow for implement smart home action now?

Should we still called report state after sync intent?

**Comment by devunwired** [comment]
Hello everyone. We recognize that this behavior has been problematic for developers in the past. We've recently updated the [Report State guide](https://developers.google.com/assistant/smarthome/develop/report-state) to reflect that this is no longer necessary to populate Home Graph.

> Following the initial `SYNC` for a device, the platform sends a `QUERY` intent that gathers the state of the device to populate Home Graph. After that point, Home Graph only stores the state that is sent with Report State.

This does not remove the need for your integration to call Report State to indicate state changes, but you do not need to make this call to populate ***initial*** state in Home Graph.
