### ISSUE TITLE
Modes in Dutch

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#230]
Hi - can I ask that for all languages that all Modes/Settings are ported? It would make sense to treat the Modes as the product, rather than the language, as pretty much all use cases will be the same, despite language.

With that in mind, can all English Modes/settings be added to Dutch and German please?

**Comment by Fleker** [comment]
All of the languages which are supported are in [this list](https://developers.google.com/actions/smarthome/traits/#supported-languages):

* Danish
* Dutch
* English
* French
* German
* Hindi
* Italian
* Japanese
* Korean
* Norwegian
* Spanish
* Swedish

I recognize that the documentation isn't showing them all right now, and I'm working on correcting that. Also, I realize that the English support has a wider variety. While we would like to have full parity, I'm definitely prioritizing specific requests, and the localization team has specific priorities as well.

I did start adding your setting requests. While most were fine, can you provide the translations of _uit_, _aan_, _weg_? I want to be sure I use the same keys as in other languages so that things are fairly portable.

**Comment by seriousme** [comment]
uit ->  off
aan -> on
weg -> away

Maybe its time to dust off some good old human computation :-)
https://www.youtube.com/watch?v=tx082gDwGcM

**Comment by madgeni** [comment]
Thanks @Fleker - i saw the language support in the documentation, but examples of the modes/settings available across language would be extremely useful :)

**Comment by madgeni** [comment]
More English + Dutch Mode requests @Fleker 

sleep - slapen
home - thuis
comfort - comfort
holidays - vakantie
guest - gasten

Also - can I ask that this: 
https://developers.google.com/actions/reference/smarthome/traits/modes#mode-settings

gets updated? It would make everyones lives easier if there was a definitive list - Thanks :)

**Comment by Fleker** [comment]
Yes, as we add new modes, we update the documentation.

**Comment by madgeni** [comment]
Cool - how do Google feel about adding brands? so Netflix/Spotify/Youtube? If ok, can we add those to all languages? Thanks!
