### ISSUE TITLE
Report error state of the device 

### ISSUE THREAD

**Issue by zoner94** [actions-on-google/smart-home-nodejs#232]
Hi, I have a misunderstanding about the Report State implementation. In some cases user can get the error of connection to the device. For example, connection is broken due auth reason (user has invalid token for that device). And i thought that i can put the "errorCode": "authFailure" field in the device object as in query or execute response and send it to the homegraph. But i can't. I get 400 error code. After that i realized the body of report state can contain only the trait attrs and the "online" field (which will be false in case above). That's why i have a situation when my fulfillment unable to report auth error state (or any other errors) to homegraph and unable to respond on query or execute queries because google side see the online = false in homegraph and does not send me that queries. 

So how i should handle such situations? Thanks

**Comment by Fleker** [comment]
Report state is meant to update the state in the HomeGraph proactively, like if the user touched a switch to turn on the light instead of using the Google Assistant.

If you want to report auth failures, you would want to return a `401` HTTP error, which is meant for auth failures. Additionally, you may want to do this in your token webhook so that the Google Assistant knows about an auth failure.

The error codes are used primarily for transmitting TTS during an _execute_. Those aren't states.

**Comment by zoner94** [comment]
It is not an auth failure on vendor side. It means that only one exact device is not available because the token for this device is invalid (every device checks some auth credentials on connection initialization). Generally the question is how to report to the user that device has a connection problem and he must to do the pairing procedure with the device. The order is: sync request from google -> retrieve devices from the vendor backend -> sync response to google -> establish connection with that devices -> if (connection is success) {do init state reporting to the home graph } else  if (connection failure) { ______?  } The last statement is unknown.

**Comment by Fleker** [comment]
The only thing of the sort that you can report is `offline`. If you have a specific connection problem with one device, you'd probably want to use your service's existing communication with the user, either through a mobile app, email, or other system. There's no status that you can report for devices otherwise.

Otherwise, if the user tries to control it, you can report the `authFailure` error code.

**Comment by zoner94** [comment]
>  if the user tries to control it, you can report the authFailure error code. 
> 
But the fulfillment unable to report the authFailure, because it doesn't receive any execute requests because homegraph has offline=false and assistant decides to talk to the user "device is unavailable right now" without communication with the fullfilment.

And i don't understand why homegraph is not allowed to know about error states of the device? After all it is the state too.
Thank you!

**Comment by Fleker** [comment]
Right now it's not considered a state. From the Google Assistant perspective, it's just one of many potential clients of a smart home service. If there's a general auth failure, that would in theory be something that should be handled by the partner as it'd break usage everywhere. While this status may be useful, it may not be possible for Google Assistant to fix itself as it'd require your own app or service.

I'll file a feature request to make this available.
