### ISSUE TITLE
Function CollectionReference.doc() undefined

### ISSUE THREAD

**Issue by ThigoPSI** [actions-on-google/smart-home-nodejs#408]
how to solve this?

http://prntscr.com/o6grv0

**Comment by Fleker** [comment]
It seems like you're trying to make a `.doc(value)` call, but `value` is undefined.

**Comment by devunwired** [comment]
Hi @ThigoPSI. From the stack trace you provided, the error is most likely occurring because there is not a valid `userId` in the database matched up with the fake access token. Did you add the user data to the database as described in the README (see [Connect to Firebase](https://github.com/actions-on-google/smart-home-nodejs#connect-to-firebase))?

I would recommend ensuring that you followed all the setup instructions, and then try again.

**Comment by proppy** [comment]
Closing as obsolete.
