### ISSUE TITLE
Hommagic: Requesting for new Modes and Settings additon for use in devices that can control more than one load

### ISSUE THREAD

**Issue by Hommagic** [actions-on-google/smart-home-nodejs#412]
Hi, 
    Greetings from Hommagic Home Automation Systems, India. Most of our products support up to 3 loads to be controlled from a single device. This means that a device with device id xyz123 can control for example, 3 lights. By using just an OnOff trait, it would be impossible to address each loads and their parameters separately. The solution here would be to use Modes. Request you to kindly add the following modes , synonyms and settings to Google Smart Home to facilitate the compatibility of such devices as ours with Google Smart Home.

Modes                                          |  Modes_Synonyms    
_________________________________________________________________________________
first switch, switch one         
second switch, switch two            
third switch, switch three      
on timer for first switch, first on timer, on timer of first switch  
on timer for second switch, second on timer, on timer of second switch  
on timer for third switch, third on timer, on timer of third switch  
off timer for first switch, first off timer, off timer of first switch      
off timer for second switch, second off timer, off timer of second switch 
off timer for third switch, third off timer, off timer of third switch 
brightness of first switch, first switch brightness, brightness of switch one
brightness of second switch, second switch brightness, brightness of switch two
brightness of third switch, third switch brightness, brightness of switch three

Settings                                 |   Settings_synonyms
_____________________________________________________________________________
activate, arm
deactivate, disarm
increase, increment
decrease, decrement
H3, 3 hour, three hour
H5, 5 hour, five hour
H6, 6 hour, six hour
H7, 7 hour, seven hour
H9, 9 hour, nine hour
H10, 10 hour, ten hour
H11, 11 hour, eleven hour
H12, 12 hour, twelve hour
H13, 13 hour, thirteen hour
H14, 14 hour, fourteen hour
H15, 15 hour, fifteen hour
H16, 16 hour, sixteen hour
H17, 17 hour, seventeen hour
H18, 18 hour, eighteen hour
H19, 19 hour, nineteen hour
H20, 20 hour, twenty hour
H21, 21 hour, twenty one hour
H22, 22 hour, twenty two  hour
H23, 23 hour, twenty three hour
H24, 24 hour, twenty four hour
M15, 15 minutes, fifteen minutes
M30, 30 minutes, thirty minutes
M45, 45 minutes, fourty five minutes, forty five minutes

Regards,
Deepak Jayakumar
Director,
Hommagic Home Automation Systems,
www.hommagicindia.com

**Comment by Fleker** [comment]
Would it make more sense to break up that device into three virtual devices that can be controlled independently?

**Comment by Hommagic** [comment]
Hi Fleker,
                thanks for getting back for our query. We have already thought about splitting up the device into multiple virtual devices. However, it complicates our device side implementations and the implementation of our official android and ios apps. We are making use of the google cloud IOT service for our products. We are also quite unsure whether Google cloud IOT allows the concept of splitting up devices into virtual devices that make use of secured MQTT connection that involves public-private key pairs for connection. (Please correct me if I am wrong) Moreover, we feel that the straight forward solution would be to implement those modes and settings into the repository. There may arise requirements as such as ours from other clients of Google in near future, looking into the trend towards the product developments in the industry. 

Regards,
Deepak Jayakumar
Director,
Hommagic Home Automation Systems,
www.hommagicindia.com

**Comment by Hommagic** [comment]
> 
> 
> Would it make more sense to break up that device into three virtual devices that can be controlled independently?
Hi Fleker,
thanks for getting back for our query. We have already thought about splitting up the device into multiple virtual devices. However, it complicates our device side implementations and the implementation of our official android and ios apps. We are making use of the google cloud IOT service for our products. We are also quite unsure whether Google cloud IOT allows the concept of splitting up devices into virtual devices that make use of secured MQTT connection that involves public-private key pairs for connection. (Please correct me if I am wrong) Moreover, we feel that the straight forward solution would be to implement those modes and settings into the repository. There may arise requirements as such as ours from other clients of Google in near future, looking into the trend towards the product developments in the industry.

Regards,
Deepak Jayakumar
Director,
Hommagic Home Automation Systems,
www.hommagicindia.com

**Comment by dtemes** [comment]
We also work with a device that supports up to 4 loads (outputs) and 4 switches (inputs). Users can connect any kind of device to the loads: lights, heaters, plug, doors/locks... so we present each load as a separate device and we use the appropriate type of device and traits for each of the channels. 

We think this is the right approach as you can leverage all the existing devices and traits. Your users will be able to access the device using standard google home application and voice commands. For instance using commands like "switch on light 1" or whatever name they give each of the virtual devices instead of changing modes and sending custom commands of your "single" device.

In our implementation when we sync the user devices we use the device id and custom attributes to store all the information that we need to send the request to the real device. For instance, if our real device has the id "ASD123" in our systems/applications and in "channel 1" the user has connected a light with the name "Red light", we give the virtual device the id "ASD123|C1" and set it to type "light". Then when a user says "turn on the red light" we will receive in our google home handler the request, which contains the device id "ASD123|C1" so we know that we have to turn on the channel 1 of the ASD123 device.

**Comment by Hommagic** [comment]
> stom attributes

Dear dtemes,
                      thanks a lot for commenting and that's so interesting to know. Do you have any links that explains in detail how these virtual devices can be set up and how the mapping of virtual to real devices can be implemented in firebase functions?

Thanks a lot in advance.

Regards,
Deepak Jayakumar
Director,
Hommagic Home Automation Systems,
www.hommagicindia.com

**Comment by dtemes** [comment]
Unfortunately we do not have any link with explanations, but it should not be complicated, if your device has 3 channels, when a user requests a device sync instead of sending back the response with a single device, just send 3 different devices. Use a composite device id that consists in the real device id plus the channel, so when you process requests you can decompose it and know which device and channel you have to act on.

David

**Comment by Hommagic** [comment]
> 
> 
> Unfortunately we do not have any link with explanations, but it should not be complicated, if your device has 3 channels, when a user requests a device sync instead of sending back the response with a single device, just send 3 different devices. Use a composite device id that consists in the real device id plus the channel, so when you process requests you can decompose it and know which device and channel you have to act on.
> 
> David

Dear David,
                  that was helpful indeed. We will try that option. Have a great weekend!
@Fleker: Thanks to you as well.

Since I feel that the solution to our issue is already here, I am closing this issue. Thanks to both of you for your support.

Regards,
Deepak Jayakumar
Director,
Hommagic Home Automation Systems,
www.hommagicindia.com
