### ISSUE TITLE
Documentation lacks many steps

### ISSUE THREAD

**Issue by veonua** [actions-on-google/smart-home-nodejs#434]
Project did not work until 

- install gcloud
- login gcloud with default credentials (?)
- login with my account
- set current project in gcloud
- install ngrok

I understand in Google office you are already has the environment, but many people do not . It would be nice to add these steps to documentation

**Comment by Fleker** [comment]
If you are using ngrok, you shouldn't need gCloud since that's only used for deploying the App Engine instance. But the README does instruct you to download the CLI if you haven't done so already.

If you're using ngork, that should be installed as a project dependency and run as part of the `npm run start:local` command.

**Comment by veonua** [comment]
have you tried without gcloud ? project fails somewhere inside smart home library 

Andrew

**Comment by Fleker** [comment]
Can you be more specific about where it fails, such as what error you're seeing and how you're running the sample?

**Comment by proppy** [comment]
Closing as obsolete.
