### ISSUE TITLE
Not connecting to endpoint

### ISSUE THREAD

**Issue by slack69** [actions-on-google/smart-home-nodejs#443]
I have set the fulfilment and oauth urls in my action and can create devices on the front-end management however whenever I try to do account linking I get the message 

`Something went wrong. Try again.`

The longs on node and ngrok are completely empty:
![image](https://user-images.githubusercontent.com/20732236/63297578-a3924d00-c2c9-11e9-8ff4-748eed4486b1.png)
![image](https://user-images.githubusercontent.com/20732236/63297604-b4db5980-c2c9-11e9-818a-0939a82cc884.png)

 as are my google logs:
![image](https://user-images.githubusercontent.com/20732236/63297514-7f367080-c2c9-11e9-8403-f4098f8b52ab.png)

This is the message I receive on my phone:
![image](https://user-images.githubusercontent.com/20732236/63297683-db999000-c2c9-11e9-8e89-6be54d3ae209.png)

I believe my fulfilment is correct:
![image](https://user-images.githubusercontent.com/20732236/63297740-f8ce5e80-c2c9-11e9-91d5-d765e1ef84d0.png)

as is my account linking:
![image](https://user-images.githubusercontent.com/20732236/63297784-17345a00-c2ca-11e9-8dfb-ffa439d027cb.png)

I have only made the changes as specified in the README.

My logs are completely barren any suggestions as to how to debug this would be very useful

**Comment by devunwired** [comment]
The fact that you are not seeing any logs in StackDriver (an issue here would typically be accompanied by an `OPEN_AUTH_FAILURE` error message) means there may be a configuration issue enabling testing in the Actions console.

Make sure you have enabled testing on your project in both of the following spots:

1. **Develop** > **Account Linking** > **Test** button at the top of the page.
1. **Test** > **Simulator**> **Start testing** on the simulator panel.

Another piece to look into is how you are launching the local dev server. The README indicates using `npm start:local` rather than just `npm start`. This may be affecting why your server isn't receiving messages as well.

**Comment by dbarwacz** [comment]
I have the same problems, while trying to add device on my phone, I see test device, select it, see that my server was hit with request but then nothing happens (screen goes back with no error message, no useful info in logs). Are there any troubleshooting steps I can take?

**Comment by dbarwacz** [comment]
#451 helped for me with this specific test, but still local component previewer does not work
