### ISSUE TITLE
Using roomHint on RequestSync

### ISSUE THREAD

**Issue by SS-TT** [actions-on-google/smart-home-nodejs#461]
Hi there!

We're using RequestSync allow the user to add new devices after the initial Sync is done, and we'd like to have those new devices to be added in their correct room.

However, this doesn't happen and, following #112, seems like `roomHint` only works in the first Sync.

Is there a way to have those newly added devices added to their rooms without needing to unlink and relink again?

**Comment by Fleker** [comment]
From the user's perspective, the devices will show up in their account in an undefined group. From there, they'd have to manually add each new device to a given room in the Home Graph.

**Comment by SS-TT** [comment]
Yeah, this is the current behavior.
I was asking if is there a way to have `roomHint` work for RequestSync too because you can't really ask to an user to manually set rooms for 20+ devices.

**Comment by devunwired** [comment]
Hi @SS-TT, since this is not an issue with the Node.js sample code, I would recommend you file this on our [public issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284148). The behavior you are describing is governed mostly by how the Google Home app responds to the data provided in SYNC (rather than the API surface itself) and we can get it routed to the right people to evaluate there.
