### ISSUE TITLE
Invalid_language_code

### ISSUE THREAD

**Issue by Moisesbr** [actions-on-google/smart-home-nodejs#462]
Hi, recently I trying to implement "action.devices.EXECUTE", but I in my body payload, locale_language is set as "invalid_language_code" how could a can change that?

example payload received:

```{
  "inputs": [
    {
      "context": { "locale_country": "BR", "locale_language": "invalid_language_code" },
      "intent": "action.devices.EXECUTE",
      "payload": {
        "commands": [
          {
            "devices": [
              {
                "customData": {
                  "bazValue": "dancing alpaca",
                  "dev": "out4",
                  "pass": "mydata"
                },
                "id": "0813bbc11e7"
              }
            ],
            "execution": [
              {
                "command": "action.devices.commands.OnOff",
                "params": { "on": true }
              }
            ]
          }
        ]
      }
    }
  ],
  "requestId": "18436418177413890633"
}

**Comment by devunwired** [comment]
Hi @Moisesbr, thanks for filing this.

Since this request is related to the smart home platform (instead of the Node.js sample code in this repo), please file this in our [public issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284148) so we can assign it to the right folks to evaluate.
