### ISSUE TITLE
Room response issue

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#478]
I've encountered an issue, and i'm not sure if it's working as expected - but I can't find any documentation on how to handle it. 
Let's say i have two switches, named Front Room Tall lamp, and Front Room Small lamp - one is in a Room called Front Room, the other is not in a room at all. Google, being clever will group them, so if i say 'turn on the front room lights' they work and the response will be something like 'ok, turning on two lights'

However, if I add the other lamp into the room, then it will tell me that one of the lights is unreachable (despite the two individual responses still being the same as before).
What am i doing wrong?

**Comment by Fleker** [comment]
So when you have Front Room Small Lamp added to "Front Room" then the same command will result in a failure? Does that device turn on?

**Comment by madgeni** [comment]
yes, both turn on, only one (it's random which) will respond correctly, for the other it will say "unable to access <light>"

It's using the OnOff trait.

**Comment by madgeni** [comment]
Any insights into this?

**Comment by Fleker** [comment]
I really don't know what's going on with that.

**Comment by madgeni** [comment]
How does Google infer the response? Nothing has changed this side, responses for each call are being sent back, but there's clearly a disconnect. 
Any insights on how to debug?

**Comment by devunwired** [comment]
There is likely an unexpected overlap in grammar between using the same name for devices and rooms. Can you file this in the [platform issue tracker](https://issuetracker.google.com/issues/new?component=655104&template=1284148) so we can investigate with the product team?

**Comment by madgeni** [comment]
thanks @devunwired - just want to make sure it's not expected, and i'm handling something incorrectly before i raise the issue with the product team. 
If I take one of the devices out, it passes two requests which then get handled correctly, otherwise all devices it deems should be in a room get handled in one request.
Happy for this to be normal practice, can we get documented expected behaviour if so?

**Comment by Fleker** [comment]
I've forwarded this to the product team to investigate.

**Comment by devunwired** [comment]
@madgeni Can I clarify one thing on your issue? In the initial comment you mentioned that the net result was that the Assistant would report an error (unreachable) for one of your devices when added to the same room. Later on the concern seems to have changed to the number of requests used.

Is the original issue of the Assistant failing to send the command to one of your lights still there, or was it mischaracterized because you didn't realize they were coming in separate intents?

**Comment by Fleker** [comment]
Can you share what your EXECUTE response looks like? It's possible that an error there may be creating the error message.

**Comment by madgeni** [comment]
@devunwired the issue seems to be that requests for devices which are deemed to be grouped now come in a single request, whereas previously each call would be an individual request. 
e.g where the front room has two lights, "turn on the front room lights" would issues two requests, whereas it now issues one (and the payload includes both calls)

**Comment by devunwired** [comment]
@madgeni I see, in that case I believe this is the expected behavior. An [EXECUTE intent](https://developers.google.com/assistant/smarthome/develop/process-intents#request_format_3) handler should be able to support multiple commands in a single intent, wherein each command can target multiple devices. Grouped devices in a single room is probably the most common example of this.

**Comment by madgeni** [comment]
Thanks - a rewrite has resolved this. Would be good to see an example request/response for different commands in the same payload :)
