### ISSUE TITLE
decimal separator issue

### ISSUE THREAD

**Issue by madgeni** [actions-on-google/smart-home-nodejs#88]
Hi - For my EU customers, it seems that Google is recognising the decimal separator as a comma, however it's kicking off an internet search, rather than interacting with a device. If you type the request, and use a point, it works - can this be looked at please?

**Comment by Fleker** [comment]
In some European countries the comma is used as the decimal separator. Can you be more specific about the commands used and the locales the users selected?

**Comment by FredVi** [comment]
HI. I'm one of the French customers that are having some issues with the decimal separator.
The command I'm using is "Règle Thermostat consigne à 19,5 degrés" (with means "Set Thermostat consigne to 19.5 degrees). And this kicks off an internet search.
If I say it "Règle Thermostat consigne à 19 degrés", it works.
I tried to **say** "Règle Thermostat consigne à 19 point 5 degrés", but 'point' is then automatically converted to 'virgule' (comma). If I **type** it (Règle Thermostat consigne à 19.5 degrés), it works.
The problem seems to come from the fact that Google the comma is not well understood by Google as the decimal separator.

**Comment by madgeni** [comment]
Hi - any eta on this?

**Comment by proppy** [comment]
Going thru the back of issues, this sounds like an general grammar issue with the Smart Home platform, and not something specific to the sample code hosted in the repo.

I order to give more visibility, I would suggest following the instructions about filing issues in the public issue tracker at https://developers.google.com/assistant/smarthome/support.
